#!/bin/bash
# 		宣告執行 script 程式用的殼程式(shell)
################## Header block ##################
# Script程式名稱
# Script Name
# 	apt-get_only-update
# 	Only update user-specified APT sources.list
# 著作權宣告
# Copyright Declaration
# 	Ｖ字龍(Vdragon) <Vdragon.Taiwan@gmail.com> (c) 2014
# 授權條款宣告
# License Declaration
# 	GNU Lesser General Public License version 3.0 or later
# 	http://www.gnu.org/licenses/lgpl.html
# 傳回值定義
# Return Value Definition
# 	0
# 		正常結束
# 已知問題
# Known Issues
# 	Known issues is now tracked on GitHub
# 	
# 修訂紀錄
# Changelog
# 	Changelog is now tracked using Git repostiory commit log
# 	
############## Header block ended ##############

######## Included files ########

######## Included files ended ########

######## File scope variable definitions ########
# idea from http://www.kfirlavi.com/blog/2012/11/14/defensive-bash-programming/
readonly PROGRAM_NAME="$(basename $0)"
readonly PROGRAM_DIRECTORY="$(readlink -m $(dirname $0))"
readonly PROGRAM_ARGUMENT_LIST="$@"
readonly PROGRAM_ARGUMENT_NUMBER_ORIGINAL=$#

######## File scope variable definitions ended ########

######## Program ########
function printUsage(){
	printf "Usage:\n"
	printf "	${PROGRAM_NAME}\n"
	printf "	${PROGRAM_NAME} <source.list file>\n"
	return
}

if [ ${PROGRAM_ARGUMENT_NUMBER_ORIGINAL} -eq 0 ]; then
	printUsage
	exit 0
else
	while (( $# )); do
		apt-get update -o Dir::Etc::sourcelist="$1" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
		shift
	done
	exit $?
fi
main
######## Program ended ########